package com.example.offlineroutingapp.offload

import android.content.Context
import android.net.Uri
import android.util.Log
import android.webkit.MimeTypeMap
import com.example.offlineroutingapp.data.entities.MessageEntity

/**
 * OffloadHelper
 *
 * Single call-site that decides whether a [MessageEntity] contains offload-able
 * media (image / document / audio) and, if so, saves it via [MediaOffloadManager]
 * and records the result in [OffloadRepository].
 *
 * Usage (from a coroutine scope, typically after inserting the message into Room):
 *
 * ```kotlin
 * OffloadHelper.maybeOffload(context, savedMessage, chatId)
 * ```
 *
 * The function is a no-op for:
 *   – Plain text messages
 *   – Messages with no imageData (Base64 payload)
 *   – Messages that were already offloaded (idempotent)
 */
object OffloadHelper {

    private const val TAG = "OffloadHelper"

    /**
     * Inspect [message] and save its media payload to device storage when applicable.
     *
     * @param context   Application or activity context.
     * @param message   The [MessageEntity] that was just persisted in Room.
     *                  Must have a valid non-zero [MessageEntity.id] (autoGenerated).
     * @param chatId    The chat this message belongs to (for OffloadRepository tagging).
     * @return          The local [Uri] where the file was saved, or null if not applicable
     *                  / already done / failed.
     */
    suspend fun maybeOffload(
        context: Context,
        message: MessageEntity,
        chatId: String
    ): Uri? {
        // Nothing to offload for plain text messages
        if (!message.isImage && !message.isAudio && !message.isDocument) return null

        // Base64 payload must be present
        val base64 = message.imageData
        if (base64.isNullOrBlank()) return null

        // Idempotency guard — skip if already saved
        if (message.id != 0L && OffloadRepository.isOffloaded(context, message.id)) {
            Log.d(TAG, "Message ${message.id} already offloaded, skipping")
            return null
        }

        val direction = if (message.isSentByMe) "sent" else "received"

        val uri: Uri? = when {
            // ── IMAGE ─────────────────────────────────────────────────────────
            message.isImage -> {
                Log.d(TAG, "Offloading image for message ${message.id}")
                MediaOffloadManager.saveImageFromBase64(context, base64, direction)
            }

            // ── AUDIO ─────────────────────────────────────────────────────────
            message.isAudio -> {
                Log.d(TAG, "Offloading audio for message ${message.id}")
                MediaOffloadManager.saveAudioFromBase64(
                    context   = context,
                    base64    = base64,
                    extension = "3gp",
                    direction = direction
                )
            }

            // ── DOCUMENT ──────────────────────────────────────────────────────
            message.isDocument -> {
                val fileName = message.documentFileName ?: "document.bin"
                val mimeType = message.documentMimeType
                    ?: mimeTypeFromFileName(fileName)
                    ?: "*/*"
                Log.d(TAG, "Offloading document '$fileName' for message ${message.id}")
                MediaOffloadManager.saveFileFromBase64(
                    context   = context,
                    base64    = base64,
                    fileName  = fileName,
                    mimeType  = mimeType,
                    direction = direction
                )
            }

            else -> null
        }

        // Record success in the repository
        if (uri != null && message.id != 0L) {
            val mediaType = when {
                message.isImage    -> OffloadRepository.MediaType.IMAGE
                message.isAudio    -> OffloadRepository.MediaType.AUDIO
                message.isDocument -> OffloadRepository.MediaType.FILE
                else               -> return uri
            }

            val displayName = when {
                message.isDocument -> message.documentFileName ?: "document"
                message.isAudio    -> "Voice Message"
                else               -> "Image"
            }

            OffloadRepository.addEntry(
                context,
                OffloadRepository.OffloadEntry(
                    messageId = message.id,
                    localUri  = uri.toString(),
                    mediaType = mediaType,
                    fileName  = displayName,
                    direction = direction,
                    savedAt   = System.currentTimeMillis(),
                    chatId    = chatId
                )
            )

            Log.d(TAG, "Offload complete: msgId=${message.id} -> $uri")
        } else if (uri == null) {
            Log.w(TAG, "Offload returned null for message ${message.id}")
        }

        return uri
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private fun mimeTypeFromFileName(fileName: String): String? {
        val ext = fileName.substringAfterLast('.', "").lowercase()
        if (ext.isEmpty()) return null
        return MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext)
    }
}
